landingi_event_store:
  event_store:
    connection: 'doctrine.dbal.default_connection' # landingi_production DB connection
  auditlog:
    enabled: true                # set to false to disable AuditLogListener
    endpoint: 'http://audit-log' # base URL endpoint for SymfonyHttpAuditLogStore
    client: 'http_client'        # instance of Symfony\Contracts\HttpClient\HttpClientInterface interface
    strict_mode: true            # set to false to ignore StrictAuditLogListener allowed events list