security:

    enable_authenticator_manager: true

    firewalls:
        api_auth:
            pattern: ^/api/auth
            stateless: true
            json_login:
                provider: auth_user_provider
                check_path: /api/auth/login
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        api:
            pattern: ^/api
            stateless: true
            provider: auth_user_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    access_control:
        - { path: ^/api/auth, roles: PUBLIC_ACCESS }
        - { path: ^/api,      roles: IS_AUTHENTICATED_FULLY }

    encoders:
        App\Entity\User: bcrypt

    providers:
        jwt:
            lexik_jwt:
                class: App\Entity\User

        auth_user_provider:
            id: api_bundle.security.auth_user_provider

    role_hierarchy:
        ROLE_USER: ROLE_USER
        ROLE_ADMIN: ROLE_USER
